version: 2.1

jobs:
  build_deps:
    parameters:
      environment:
        type: string
        default: ""
    docker:
      - image: circleci/python
    steps:
      - checkout:
          path: ~/test
      - run:
          command: ls -la
          working_directory: ~/test/<< parameters.environment >>

workflows:
  version: 2
  build:
    jobs:
      - build_deps:
          name: first
          environment: prod
      - build_deps:
          name: second
          environment: stg
