version: 2.1

jobs:
  build_deps:
    parameters:
      environment:
        type: string
      var:
        type: string
    environment:
      TF_VAR_test: << parameters.var >>
    docker:
      - image: circleci/python
    steps:
      - checkout:
          path: ~/test
      - run:
          command: pwd
          working_directory: ~/test/<< parameters.environment >>
      - run:
          command: ls -la
          working_directory: ~/test/<< parameters.environment >>
      - run:
          command: echo "${TF_VAR_test}"

workflows:
  version: 2
  build:
    jobs:
      - build_deps:
          name: first
          environment: prod
          var: onsiter_image=eu.gcr.io/test/app:${CIRCLE_BRANCH}-${CIRCLE_SHA1}
      - build_deps:
          name: second
          environment: stg
          var: onsiter_image=eu.gcr.io/test/app:${CIRCLE_BRANCH}-${CIRCLE_SHA1}
